version: "3.9"

services:

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - admin-service
      - auth-service
      - user-service
      - user-service-2
      - user-service-3
    networks:
      - distributed-gateway-network
    restart: unless-stopped

  gateway-dashboard:
    build:
      context: ./gateway-dashboard
      dockerfile: Dockerfile
    container_name: gateway-dashboard
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production
    depends_on:
      - gateway
    networks:
      - distributed-gateway-network
    restart: unless-stopped

  admin-service:
    build:
      context: ./services/admin-service
      dockerfile: Dockerfile
    container_name: admin-service
    environment:
      NODE_ENV: production
      PORT: 5005
    expose:
      - "5005"
    depends_on:
      - auth-service
    networks:
      - distributed-gateway-network
    restart: unless-stopped

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      NODE_ENV: production
      PORT: 5001
    expose:
      - "5001"
    depends_on:
      - user-service
    networks:
      - distributed-gateway-network
    restart: unless-stopped

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      NODE_ENV: production
      PORT: 5002
    expose:
      - "5002"
    depends_on:
      - user-service-2
      - user-service-3
    networks:
      - distributed-gateway-network
    restart: unless-stopped

  user-service-2:
    build:
      context: ./services/user-service-2
      dockerfile: Dockerfile
    container_name: user-service-2
    environment:
      NODE_ENV: production
      PORT: 5003
    expose:
      - "5003"
    networks:
      - distributed-gateway-network
    restart: unless-stopped

  user-service-3:
    build:
      context: ./services/user-service-3
      dockerfile: Dockerfile
    container_name: user-service-3
    environment:
      NODE_ENV: production
      PORT: 5004
    expose:
      - "5004"
    networks:
      - distributed-gateway-network
    restart: unless-stopped

networks:
  distributed-gateway-network:
    driver: bridge